agents:
  - name: general-purpose
    description: "General-purpose agent for complex, multi-step tasks that require research, analysis, and synthesis. Use this when you need to handle tasks that involve multiple searches, gathering information from various sources, or autonomous multi-step workflows."
    prompt:
      - prompts/subagents/general-purpose.md
    tool_output_max_tokens: 10000
    llm: haiku-4.5
    tools:
      - impl:*:*
      - internal:*:*
      - mcp:*:*

  - name: explorer
    description: "Specialized agent for exploring codebases to understand structure, find implementations, and analyze code patterns. Use this when you need to find where functionality is implemented, understand code organization, or explore how components work."
    prompt:
      - prompts/prefixes/notes.md
      - prompts/subagents/explorer.md
      - prompts/suffixes/environments.md
    llm: haiku-4.5
    tool_output_max_tokens: 10000
    tools:
      - impl:*:*
      - internal:*:*
      - mcp:*:*
